### ISSUE TITLE
Option to hide [Admin mode] link?

### ISSUE THREAD

**Issue by catharsis71** [satopian/poti-kaini-EN#8]
I have the admin page IP-restricted so whenever someone who isn't me clicks the [Admin mode] link, it generates 403 errors as well as alerts from my WAF

Most of the time it's not even humans clicking the link, it's just web crawlers following every link on the page

I would like an option to hide this link to cut down on the number of alerts I get about it

**Comment by satopian** [comment]
[v5.63.8 #8 · satopian/poti-kaini-EN@e96d3eb](https://github.com/satopian/poti-kaini-EN/commit/e96d3eb6bb38a5c6c43a05d131c1d4ed47a1708f)

```
// Display a link to the [Admin mode]  Yes: 1 No: 0
define("USE_ADMIN_LINK", "1");
// No: 0 hides the link the admin mode.

```
made an option.
does this work for you?

**Comment by catharsis71** [comment]
great, thank you
